LexemeNotFoundException: Add default $message
And avoid passing null to the parent constructor, which is deprecated in
PHP 8.1. (Compare Wikibase change I74d381c335, commit 9bb7e78524.)

Bug: T319219
Change-Id: I7f643933dce7fdd96dfa58c5e23a963e46f28a14